-- CTK-109 — drop orphan get_recent_price_drops() RPC.
--
-- Background: migration 0008 created get_recent_price_drops() as the /deals
-- LAG-window query. Migration 0027 (CTK-047 B-1 + CTK-109 widen) introduced
-- get_listing_drop_context(listing_ids bigint[], window_hours int) — a
-- generalized superset that answers the same fleet-wide question when called
-- with (NULL, 24), and also serves CTK-047 B-3 cross-surface per-listing
-- callers. C2 equivalence verified at cf7e2ff against Neon — fleet-wide
-- behavior byte-for-byte preserved, plus compare_at_price now in the
-- projection.
--
-- After /deals call-site swap (lib/queries/listings.ts getRecentPriceDrops()
-- now calls get_listing_drop_context(NULL, 24)), get_recent_price_drops()
-- has no remaining callers. This migration drops it.
--
-- ─── Apply ordering (NOT pre-deploy) ───
--
-- Apply this migration AFTER the /deals swap has deployed and smoke-passed:
--
--   1. Code commit + PR merge + Vercel deploy of the swap.
--   2. Eyeball /deals against live data — rows 36786 / 37391 render
--      vendor-markdown medal alongside the price-drop medal.
--   3. THEN apply this migration via scripts/apply_migration_0028.py (or the
--      same /backend-engineer-routed apply path migration 0027 took at
--      cf7e2ff).
--
-- Pre-deploy apply would 5xx /deals because the call-site swap hasn't shipped
-- yet — the old function vanishes while production still references it.
-- Post-deploy apply is safe: the function is orphan at that point.
--
-- DROP IF EXISTS is idempotent — re-apply is a no-op.

DROP FUNCTION IF EXISTS get_recent_price_drops();
